title: PHP MVC Template
description: Template profesional para aplicaciones web PHP con patrón MVC
theme: jekyll-theme-cayman

# GitHub repository
repository: tu-usuario/tu-repo

# Base URL
baseurl: ""
url: ""

# Plugins
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Permalink structure
permalink: /:title.html

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.sh"
  - "README.md"

# Default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation
navigation:
  - title: "Inicio"
    url: "/"
  - title: "Instalación"
    url: "/Installation.html"
  - title: "Tutorial CRUD"
    url: "/CRUD-Tutorial.html"
  - title: "CI/CD"
    url: "/CI-CD-Workflow.html"
