title: PHP MVC Template
description: Template profesional para aplicaciones web PHP con patrón MVC
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.sh"
  - "README.md"
